#!/usr/bin/env python

from __future__ import print_function

from argparse import ArgumentParser
from subprocess import call


def requirements(dev=None):
    cmd = [
        'pip-compile requirements/requirements.in',
        'echo "-r requirements-range.txt # manually added by cli" >> requirements/requirements.txt'
    ]

    if dev:
        cmd = ['pip-compile requirements/requirements-testing.in']

    for c in cmd:
        call(c, shell=True)


def main():
    parser = ArgumentParser()
    parser.add_argument('function', help='name of function to run', choices=['req'])
    parser.add_argument('-t', '--testing', help='generate requirements for testing', action='store_true', default=False)

    options = parser.parse_args()
    switcher = {
        'req': lambda: requirements(options.testing)
    }

    func = switcher.get(options.function, None)
    if func:
        func()


if __name__ == '__main__':
    main()
